result_file_prefix:
    #Prefix for output files to uniquely identify related outputs. Please
    #keep the prefix short and avoid using special characters such as periods
    #or commas.
    "breotest"

contig_directory:
    #Path to directory containing contigs
    "/Users/parevalo/RiboTree/test-genomes/"
contig_extension:
    #Extension for genome files. NOTE THAT THIS PIPELINE EXPECTS ALL GENOME FILES TO FOLLOW 
    #THE SAME NAMING CONVENTION:
    #
    #    {strain name}.{extension}
    #
    #For example, if we have two strains (FF50 and 9C6106) that we would like to
    #include in this pipeline, then the following are acceptable examples of filenames:
    #FF50.fasta, 9CS106.fasta (Extension in this case is .fasta)
    #FF50_contigs.fasta, 9CS106_contigs.fasta (Extension in this case is ls .fasta)
    ".fasta"
output_directory:
    #Directory for pipeline outputs. Will be created if it does not already exist
    "pcc/outputs/"
outgroup_genome:
    #Path to outgroup genome
    #"/home/parevalo/scratch/genomes_for_clustering/inputs/Vib/clean/9CS106_contigs_for_pipeline.fa"
    "/Users/parevalo/RiboTree/test-outgroup/pseudo_PAO1.fasta"
script_location:
    #Path to directory containing scripts. Can be an absolute or
    #relative path. Please make sure the path ends in a /
    "scripts/"
ribo_hmm_file:
    #Path to ribosomal hmm file
    "hmmfiles/Yutin_Ribosomal_Proteins.hmm"
raxml_params: 
    #Parameters for RaxML. See RaxML documentation for more information.
    "-f a -x 26789416 -m GTRGAMMAX -p 218957 -# 10 -o outgroup_genome"
min_col_frac:
    #Parameter that determines how to filter the final alignment. If min_col_frac = 0.5,
    #Then any alignment columns that contain > 50% gaps will be eliminated. 
    "0.5"
