name: RiboTree
channels:
- biocore
- bioconda
dependencies:
- dropbox=5.2.1=py35_0
- filechunkio=1.6=py35_0
- ftputil=3.2=py35_0
- pysftp=0.2.8=py35_0
- snakemake=3.7.1=py35_0
- urllib3=1.12=py35_0
- hmmer=3.1b2=0
- mafft=7.245=0
- biopython=1.67=np111py35_0
- docutils=0.12=py35_2
- ecdsa=0.13=py35_0
- libgcc=5.2.0
- mkl=11.3.3=0
- numpy=1.11.1=py35_0
- openssl=1.0.2h=1
- paramiko=1.16.0=py35_0
- pip=8.1.2=py35_0
- pycrypto=2.6.1=py35_4
- python=3.5.2=0
- pyyaml=3.11=py35_4
- raxml=8.2.9
- readline=6.2=2
- requests=2.10.0=py35_0
- setuptools=23.0.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - dropbox==5.2.1
  - filechunkio==1.6
  - ftputil==3.2
  - pysftp==0.2.8
  - snakemake==3.7.1
  - urllib3==1.12

